### ISSUE TITLE
Token list should comply with SEP-0042

### ISSUE THREAD

**Issue by esteblock** [soroswap/token-list#19]
SEP-0042 is a proposal standart
In order to comply with it we need to use `assets` instead of `tokens`, and also add some other metadata, please check
SEP-0042 [spec](https://github.com/orbitlens/stellar-protocol/blob/sep-0042-token-lists/ecosystem/sep-0042.md).
https://github.com/stellar/stellar-protocol/pull/1440/files

**Comment by joaquinsoza** [comment]
#20
